### ISSUE TITLE
Example code has retain cycle

### ISSUE THREAD

**Issue by griffin-stewie** [takasek/Notifwift#11]
Thank you for providing this library to us. It looks helpful when I use Notifiacation(a.k.a. `NSNotification`) .

However I found a little mistake on your README. The section [Real World Example](https://github.com/takasek/Notifwift#real-world-example) tells me 

```
The Notifwift instance is alive during MyViewController instance. It dies when MyViewController instance dies, so observers registered in the Notifwift instance are to be removed automatically. Never mind if you have to manage observer!
```

but this example code, `MyViewController` never dies, because you pass the  function directory. This means function's owner captured by closure. You should do like this 

``` swift
notifwift.observe(didReceiveUserNotification) { [weak self] (user: User) in
    self?.userInfoView.reload(user)
}
```
- Pass a closure (not func) to avoid capturing `self`.
- Use `[weak self]` to avoid capturing `self` when you access IVar, actuary We must put `self` when we access IVar inside a closure though.

**Comment by takasek** [comment]
@griffin-stewie 
It's exactly as you said.
I'd realized the mistake of my code([君の参照は。〜classとfunctionと循環参照の話〜 // Speaker Deck](https://speakerdeck.com/takasek/jun-falsecan-zhao-ha-classtofunctiontoxun-huan-can-zhao-falsehua)
), but forgotten to fix the README... 
Thank you for pointing out.
I'm to fix the code as soon as possible.

**Comment by takasek** [comment]
I fixed the documents on both `master` & `swift-2.3` branches.

https://github.com/takasek/Notifwift/commit/74de31b47b3e80a79a0366e4b31c2269344b22e1 https://github.com/takasek/Notifwift/commit/537a5d2f383aed93d0625068191a19d4f1cbafbb

Thank you a lot!
