### ISSUE TITLE
Support for Swift 2.3 and 3.0

### ISSUE THREAD

**Issue by elprl** [takasek/Notifwift#5]
Advise two branches for swift2.3 and swift3.0.

**Comment by takasek** [comment]
Thank you for advise.  I'm getting ready as soon as possible.

**Comment by takasek** [comment]
@elprl 
Updated master branch for Swift3.0,
and created [swift-2.3 branch](https://github.com/takasek/Notifwift/tree/swift-2.3).

**Comment by elprl** [comment]
I'm seeing error on code 
`notifwift.observe(Constants.Notifs.RACE_CARD_QUERY_LOADED) { [weak self] notification in`
with swift3 fixit changing to 
`notifwift.observe(Notification.Name(rawValue: Constants.Notifs.RACE_CARD_QUERY_LOADED)) { [weak self] notification in`
Is that correct? 
If so, you may need to change documentation.

**Comment by takasek** [comment]
@elprl 

Is your code like below?

``` swift
struct Constants {
    struct Notifs {
        static var RACE_CARD_QUERY_LOADED = "RACE_CARD_QUERY_LOADED"
    }
}

class YourClass {
    let notifwift = Notifwift()
    init() {
        notifwift.observe(Constants.Notifs.RACE_CARD_QUERY_LOADED) { [weak self] notification in
            //...
        }
    }
}
```

Then, what about to migrate in such way?

``` swift
struct Constants {
    struct Notifs {
        static var RACE_CARD_QUERY_LOADED = Notification.Name(rawValue: "RACE_CARD_QUERY_LOADED")
    }
}
```

[The migration guide](https://swift.org/migration-guide/) says,

> In Swift 3, many of Foundation’s “stringly-typed” APIs have been changed to use struct “wrapper types”, such as the new Notification.Name type. Since, it’s common for notification names and other string constants to be declared globally or as static members, the best way to take advantage of these new types is usually to construct the wrapper at the point of declaration:
> 
> ``` swift
> static let MyGreatNotification = Notification.Name("MyGreatNotification")
> // Use site (no change)
> NotificationCenter.default().post(name: MyController.MyGreatNotification, object: self)'
> ```

So Notifwift doesn't care of the backward compatibility.
Notifwift in Swift3 accepts `Notification.Name` rather than the String literal.

Anyway, thank you to the question about migration.
I'm to add the migration guide written above to `README.md` .

**Comment by takasek** [comment]
I found that current `README.md` has a code which defines the notification name as the string literal!
https://github.com/takasek/Notifwift/blame/9bdd0e8eff5af474c883d4705ba31090a6af7d91/README.md#L145

@elprl, you told me the fault!  Thank you very much.
